// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.3
// source: lindell-signing.proto

package signing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a P2P message sent to each party during Round 1 of the ECDSA TSS signing protocol.
type SignRound1Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N        []byte `protobuf:"bytes,1,opt,name=N,proto3" json:"N,omitempty"`
	Share    []byte `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	FirstMsg []byte `protobuf:"bytes,3,opt,name=firstMsg,proto3" json:"firstMsg,omitempty"`
}

func (x *SignRound1Message) Reset() {
	*x = SignRound1Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lindell_signing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRound1Message) ProtoMessage() {}

func (x *SignRound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_lindell_signing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRound1Message.ProtoReflect.Descriptor instead.
func (*SignRound1Message) Descriptor() ([]byte, []int) {
	return file_lindell_signing_proto_rawDescGZIP(), []int{0}
}

func (x *SignRound1Message) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *SignRound1Message) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *SignRound1Message) GetFirstMsg() []byte {
	if x != nil {
		return x.FirstMsg
	}
	return nil
}

// Represents a P2P message sent to each party during Round 2 of the ECDSA TSS signing protocol.
type SignRound2Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rst []byte `protobuf:"bytes,1,opt,name=rst,proto3" json:"rst,omitempty"`
}

func (x *SignRound2Message) Reset() {
	*x = SignRound2Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lindell_signing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRound2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRound2Message) ProtoMessage() {}

func (x *SignRound2Message) ProtoReflect() protoreflect.Message {
	mi := &file_lindell_signing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRound2Message.ProtoReflect.Descriptor instead.
func (*SignRound2Message) Descriptor() ([]byte, []int) {
	return file_lindell_signing_proto_rawDescGZIP(), []int{1}
}

func (x *SignRound2Message) GetRst() []byte {
	if x != nil {
		return x.Rst
	}
	return nil
}

var File_lindell_signing_proto protoreflect.FileDescriptor

var file_lindell_signing_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x69, 0x6e, 0x64, 0x65, 0x6c, 0x6c, 0x2d, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6c, 0x69, 0x6e, 0x64, 0x65, 0x6c, 0x6c,
	0x2e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x53, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x4e, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x25, 0x0a,
	0x11, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x72, 0x73, 0x74, 0x42, 0x11, 0x5a, 0x0f, 0x6c, 0x69, 0x6e, 0x64, 0x65, 0x6c, 0x6c, 0x2f,
	0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lindell_signing_proto_rawDescOnce sync.Once
	file_lindell_signing_proto_rawDescData = file_lindell_signing_proto_rawDesc
)

func file_lindell_signing_proto_rawDescGZIP() []byte {
	file_lindell_signing_proto_rawDescOnce.Do(func() {
		file_lindell_signing_proto_rawDescData = protoimpl.X.CompressGZIP(file_lindell_signing_proto_rawDescData)
	})
	return file_lindell_signing_proto_rawDescData
}

var file_lindell_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lindell_signing_proto_goTypes = []interface{}{
	(*SignRound1Message)(nil), // 0: lindell.signing.SignRound1Message
	(*SignRound2Message)(nil), // 1: lindell.signing.SignRound2Message
}
var file_lindell_signing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lindell_signing_proto_init() }
func file_lindell_signing_proto_init() {
	if File_lindell_signing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lindell_signing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignRound1Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lindell_signing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignRound2Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lindell_signing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lindell_signing_proto_goTypes,
		DependencyIndexes: file_lindell_signing_proto_depIdxs,
		MessageInfos:      file_lindell_signing_proto_msgTypes,
	}.Build()
	File_lindell_signing_proto = out.File
	file_lindell_signing_proto_rawDesc = nil
	file_lindell_signing_proto_goTypes = nil
	file_lindell_signing_proto_depIdxs = nil
}
